### ISSUE TITLE
Answering queries with CQD Error

### ISSUE THREAD

**Issue by Joyrocky** [uclnlp/cqd#4]
When I have trained the model, I followed the the path to answer the question but it showed that missing the entity2text.text .Could you please give some suggestions to slove the problems? thx!😊

![image](https://user-images.githubusercontent.com/23481533/127423945-fe7c25f0-670b-4e65-b9ad-6a76831071ec.png)

**Comment by dfdazac** [comment]
@Joyrocky thank you for pointing this out!
I have merged a fix for this, please let me know if you still have any issues with the code after pulling the changes.

**Comment by pminervini** [comment]
Hi @Joyrocky, we also implemented CQD in the KGReasoning framework, which supports experimenting with the Query2Box and BetaE datasets; our code is available at this link: https://github.com/pminervini/KGReasoning/

**Comment by Joyrocky** [comment]
> @Joyrocky thank you for pointing this out!
> I have merged a fix for this, please let me know if you still have any issues with the code after pulling the changes.

![image](https://user-images.githubusercontent.com/23481533/131770485-0f885751-e480-484a-b155-2fa687a9b8ff.png)
![image](https://user-images.githubusercontent.com/23481533/131770554-135e3dbe-5209-4a77-a36a-e7a049ca1c85.png)
I am sorry to bother that when I run the answering step, there is always a collapse about the memory, do you have some suggestions for me to solve this, thx!

**Comment by pminervini** [comment]
Thank you for getting back, let me look into this

**Comment by pminervini** [comment]
Hello @Joyrocky, setting the number of candidates (`k` in the paper, ` --candidates` flag on the command line) to e.g. 4 fixes the problem! Try replacing ` --candidates 64` with ` --candidates 4`, and everything should be fine.

On a side note, you may want to a different value of `k` for each different query type: in most cases, using very large `k` values will work very well in terms of downstream accuracy, and the GPU memory usage will be feasible. The code on this repo needs to be adapted a bit (I can do it this weekend), but the `KGReasoning` repo I linked earlier allows to do this already.

**Comment by Joyrocky** [comment]
> Hello @Joyrocky, setting the number of candidates (`k` in the paper, ` --candidates` flag on the command line) to e.g. 4 fixes the problem! Try replacing ` --candidates 64` with ` --candidates 4`, and everything should be fine.
> 
> On a side note, you may want to a different value of `k` for each different query type: in most cases, using very large `k` values will work very well in terms of downstream accuracy, and the GPU memory usage will be feasible. The code on this repo needs to be adapted a bit (I can do it this weekend), but the `KGReasoning` repo I linked earlier allows to do this already.

Ok, I have get it. Then I got this, maybe this module have some redundant code?
![image](https://user-images.githubusercontent.com/23481533/131940348-15ab40e8-5c78-47c1-bf35-993770cd0d49.png)

**Comment by PavlidisAris** [comment]
Hello @pminervini ,
When I'm executing your program, at any model you have, even if I'm training any model again, I'm receiving the error showed in this picture. Do you know how could I fix it? 
Thanks a lot
![2022-05-11](https://user-images.githubusercontent.com/36454047/167888425-00a3793f-d5ab-4aae-8ca2-471d631a16d3.png)

**Comment by pminervini** [comment]
@osoblanco this was resolved in the past, right?

@PavlidisAris @Joyrocky, we incorporated CQD in the KGReasoning framework, it may be easier to use that instead: https://github.com/pminervini/KGReasoning/

**Comment by osoblanco** [comment]
@PavlidisAris it seems that the error occurs because at least one of the tasks you are trying/training/inferring with is outside the set we provide here

https://github.com/uclnlp/cqd/blob/36148c110f336415250c98873fc27ca847741a78/kbc/utils.py#L141

Can you please share the command you are using ? It seems the `graph_type` is incorrect.

**Comment by PavlidisAris** [comment]
> @PavlidisAris it seems that the error occurs because at least one of the tasks you are trying/training/inferring with is outside the set we provide here
> 
> https://github.com/uclnlp/cqd/blob/36148c110f336415250c98873fc27ca847741a78/kbc/utils.py#L141
> 
> Can you please share the command you are using ? It seems the `graph_type` is incorrect.

Thanks for your rapidly answer
The command that I'm using is:
!python3 kbc/cqd_beam.py --model_path models/NELL-model-rank-100-epoch-50-1602489428.pt --dataset NELL --mode test --t_norm product --candidates 8 --scores_normalize 0 data/NELL

This is the last command. I tried much more commands depending the model I use, but the problem still remains.

**Comment by PavlidisAris** [comment]
Dear Pasquale,

Thanks for your suggestion for the KGReasoning framework. It works well. I reduce some parameters of a command in order of faster loading. The model loaded completely. Now, what? How can I ask the model a question? Are there any demo for viewing?

Thanks for your time
Aris
________________________________

**Comment by pminervini** [comment]
@PavlidisAris sure! Here's how to use the CQD implementation in KGReasoning on the validation and test complex queries: https://github.com/pminervini/KGReasoning/blob/main/CQD.md

**Comment by PavlidisAris** [comment]
Thank you very much for your quick answer. I'm sure that I don't understand very good something. I'm running a model in cmd environment, it's completely loaded and that's it. Nothing moreover happens. How can I ask a question to the model?
Thanks for your time.

Aris


________________________________
Από: Pasquale Minervini ***@***.***>
Eστάλη: Τρίτη, 7 Ιουνίου 2022, 09:37
Προς: uclnlp/cqd ***@***.***>
Κοιν.: PavlidisAris ***@***.***>; Mention ***@***.***>
Θέμα: Re: [uclnlp/cqd] Answering queries with CQD Error (#4)


@PavlidisAris<https://github.com/PavlidisAris> sure! Here's how to use the CQD implementation in KGReasoning on the validation and test complex queries: https://github.com/pminervini/KGReasoning/blob/main/CQD.md

**Comment by pminervini** [comment]
@PavlidisAris the code is not supposed to work interactively -- what command line did you use?

**Comment by PavlidisAris** [comment]
Good morning Pasquale,
The command that I was used is shown below
 python3 main.py --do_test --data_path data/FB15k-q2b -n 1 -b 1000 -d 1000 --cpu_num 0 --geo cqd --tasks 1p --print_on_screen --test_batch_size 1 --checkpoint_path models/fb15k-q2b --cqd discrete

Using the above command, the data loaded correctly, the evaluation of dataset completely OK and that's all. After all, I want to ask e.g. the question of your paper, you know this one: “In what genres of moviesdid Martin Lawrence appear?”
My question is "how can I do that?" 
Depending of your previous answer, I can't, if I'm understanding well.
I'm postgraduate student and your work is my homework. I'd like to show a demo how this program is working if it possible.
Thanks a lot
Aris



    Στις Τετάρτη 8 Ιουνίου 2022, 08:51:20 π.μ. EEST, ο χρήστης Pasquale Minervini ***@***.***> έγραψε:  
 
 


@PavlidisAris the code is not supposed to work interactively -- what command line did you use?

**Comment by pminervini** [comment]
@PavlidisAris I see! Interactive mode is not supported atm, the code "only" allows you to evaluate on a set of validation and test queries.

Maybe the easiest way to go about this is to create a new test dataset containing your test query, and edit the code to e.g. print the top `k` answers together with their score

**Comment by PavlidisAris** [comment]
Thank you very very much for your answers and for your time.

Λήψη Outlook για Android<https://aka.ms/AAb9ysg>
________________________________
